### ISSUE TITLE
Yugioh模擬器開發人員聊天。

### ISSUE THREAD

**Issue by PixelatedProphet** [Hope-Phenom/YGOPro2MDPro#1]
我們對您的項目感興趣，希望您加入我們的開發人員聊天。 我們有來自Salvation，Edopro，Dueling Book，Dueling Nexus，Mycard和其他人的開發人員。
https://discord.gg/wUjrTS4

**Comment by Hope-Phenom** [comment]
> 我們對您的項目感興趣，希望您加入我們的開發人員聊天。 我們有來自Salvation，Edopro，Dueling Book，Dueling Nexus，Mycard和其他人的開發人員。 https://discord.gg/wUjrTS4

您好，我已加入该频道，希望以后可以为ygo模拟器的维护贡献一份力量。
